#!/usr/bin/env bash
# a script that configures HAproxy in a load balancer 

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo chown -R $USER:$USER /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 18106-web-01 35.174.61.107:80 check\n\tserver 18106-web-02 3.209.80.161:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
