#!/usr/bin/env bash
# manage_my_process Bash script
#+	Indefinitely writes I am alive! to the file /tmp/my_process
#+	In between every I am alive! message, sleep 2secs

while true; do
    sudo bash -c 'echo "I am alive!" >> /tmp/my_process'
    sleep 2
done
